# Generated by Django 4.2.28 on 2026-02-06 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('silence_threshold', models.FloatField(default=0.5)),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('population', models.IntegerField()),
                ('complaints', models.IntegerField()),
                ('history_avg', models.IntegerField()),
                ('density', models.FloatField(blank=True, null=True)),
                ('density_z', models.FloatField(blank=True, null=True)),
                ('is_silent', models.BooleanField(default=False)),
                ('trend_gap', models.FloatField(blank=True, null=True)),
                ('fear_score', models.FloatField(blank=True, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.uploadeddataset')),
            ],
        ),
    ]
